-- Baseline: the schema exactly as Hibernate's ddl-auto=update built it, captured from a
-- live boot of the pre-Flyway application on 2026-09-04.
--
-- This migration DOES NOT RUN on the existing Railway database. That database predates
-- Flyway, so it is stamped at version 1 by spring.flyway.baseline-on-migrate and picks up
-- from V2. This file exists so a fresh environment (a new dev box, a staging database,
-- a rebuilt production) arrives at the same starting point instead of depending on
-- Hibernate to guess the schema.
--
-- The odd constraint names (uk404ft..., fk67dak...) are Hibernate's own generated names.
-- They are reproduced verbatim so a fresh database is identical to production rather than
-- merely equivalent to it. Do not tidy them.

CREATE TABLE tutors (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    area                VARCHAR(255),
    batch_type          VARCHAR(255),
    bio                 VARCHAR(1000),
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    email               VARCHAR(255),
    full_address        VARCHAR(500),
    latitude            DOUBLE PRECISION,
    locality            VARCHAR(255),
    longitude           DOUBLE PRECISION,
    name                VARCHAR(255),
    password_hash       VARCHAR(255),
    phone               VARCHAR(255),
    photo_url           VARCHAR(255),
    price               INTEGER,
    price_type          VARCHAR(255),
    price_unit          VARCHAR(255),
    qualification       VARCHAR(255),
    status              VARCHAR(255) NOT NULL,
    trial_available     BOOLEAN,
    video_url           VARCHAR(255),
    years_experience    INTEGER,
    CONSTRAINT tutors_pkey PRIMARY KEY (id),
    CONSTRAINT ukcx2524pmv5o93f0aihe1o8lgp UNIQUE (email),
    CONSTRAINT tutors_status_check CHECK (status IN ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED'))
);

CREATE TABLE tutor_modes (
    tutor_id BIGINT NOT NULL,
    mode     VARCHAR(255),
    CONSTRAINT fk67dakvj3ga6705i8vpyw4guma FOREIGN KEY (tutor_id) REFERENCES tutors (id)
);

CREATE TABLE tutor_tuition_types (
    tutor_id     BIGINT NOT NULL,
    tuition_type VARCHAR(255),
    CONSTRAINT fk7koo52qf24a6f9h6holdtlrnn FOREIGN KEY (tutor_id) REFERENCES tutors (id)
);

CREATE TABLE tutor_grade_subjects (
    tutor_id BIGINT NOT NULL,
    grade    VARCHAR(255),
    subjects VARCHAR(255),
    CONSTRAINT fkkjde346xmoikbvfk4if9c4ocm FOREIGN KEY (tutor_id) REFERENCES tutors (id)
);

CREATE TABLE tutor_timings (
    tutor_id BIGINT NOT NULL,
    timing   VARCHAR(255),
    CONSTRAINT fkgrmc4on52x2n2a08vsjotnh0t FOREIGN KEY (tutor_id) REFERENCES tutors (id)
);

CREATE TABLE tutor_languages (
    tutor_id BIGINT NOT NULL,
    language VARCHAR(255),
    CONSTRAINT fktm9xwxq6yy34fe9tl4y40o1o6 FOREIGN KEY (tutor_id) REFERENCES tutors (id)
);

CREATE TABLE enquiries (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    accepted_at         TIMESTAMP(6) WITH TIME ZONE,
    budget              VARCHAR(255),
    class_name          VARCHAR(255),
    completed_at        TIMESTAMP(6) WITH TIME ZONE,
    connected_at        TIMESTAMP(6) WITH TIME ZONE,
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    declined_at         TIMESTAMP(6) WITH TIME ZONE,
    locality            VARCHAR(255),
    message             VARCHAR(1000),
    mode                VARCHAR(255),
    parent_name         VARCHAR(255) NOT NULL,
    parent_phone        VARCHAR(255) NOT NULL,
    preferred_timing    VARCHAR(255),
    public_token        VARCHAR(255) NOT NULL,
    status              VARCHAR(255) NOT NULL,
    subject             VARCHAR(255),
    tuition_started_at  TIMESTAMP(6) WITH TIME ZONE,
    tutor_id            BIGINT NOT NULL,
    updated_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    viewed_at           TIMESTAMP(6) WITH TIME ZONE,
    whatsapp_clicked_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT enquiries_pkey PRIMARY KEY (id),
    CONSTRAINT uk404ft0isn3k1lr7379yttwapj UNIQUE (public_token),
    CONSTRAINT enquiries_status_check CHECK (status IN ('NEW', 'VIEWED', 'ACCEPTED', 'DECLINED',
                                                        'CONNECTED', 'TUITION_STARTED', 'COMPLETED', 'EXPIRED'))
);

CREATE TABLE analytics_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_type  VARCHAR(255) NOT NULL,
    occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    tutor_id    BIGINT NOT NULL,
    CONSTRAINT analytics_events_pkey PRIMARY KEY (id),
    CONSTRAINT analytics_events_event_type_check CHECK (event_type IN ('PROFILE_VIEWED', 'REQUEST_STARTED'))
);
