-- Phase 1: reference tables for subject, grade and locality.
--
-- Until now a tutor's teaching scope lived in tutor_grade_subjects as free text:
-- grade "Class 6 - Class 8", subjects "Math, Science". That cannot be searched — which is
-- why the site can filter by help-type and mode but not by subject or grade, the single
-- biggest gap in the product. These tables give those concepts real identity so Phase 2
-- can filter on them.
--
-- Table names are plural to match the tables already here (tutors, enquiries,
-- analytics_events), not the singular names in the roadmap sketch.

CREATE TABLE subjects (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(80) NOT NULL,
    slug          VARCHAR(80) NOT NULL,
    sort_order    INTEGER NOT NULL DEFAULT 0,
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT subjects_pkey PRIMARY KEY (id),
    CONSTRAINT uq_subjects_name UNIQUE (name),
    CONSTRAINT uq_subjects_slug UNIQUE (slug)
);

CREATE TABLE grades (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(40) NOT NULL,
    slug          VARCHAR(40) NOT NULL,
    -- Ascending teaching order (Nursery lowest). Lets us ask "grade between X and Y"
    -- without parsing names, and keeps dropdowns in a sane order.
    sort_order    INTEGER NOT NULL,
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT grades_pkey PRIMARY KEY (id),
    CONSTRAINT uq_grades_name UNIQUE (name),
    CONSTRAINT uq_grades_slug UNIQUE (slug)
);

-- Localities are seeded by name only (see V4). Coordinates are filled in afterwards by an
-- explicit geocoding pass against Google Places, because guessed coordinates would
-- silently misrank "nearest tutor" and there would be no way to tell which rows were wrong.
-- geocoded_at NULL therefore means "not yet resolved", not "has no location".
CREATE TABLE localities (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(120) NOT NULL,
    city           VARCHAR(60) NOT NULL,
    latitude       DOUBLE PRECISION,
    longitude      DOUBLE PRECISION,
    geocoded_at    TIMESTAMP(6) WITH TIME ZONE,
    geocode_note   VARCHAR(255),
    active         BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT localities_pkey PRIMARY KEY (id),
    CONSTRAINT uq_localities_name_city UNIQUE (name, city),
    CONSTRAINT ck_localities_city CHECK (city IN ('Chandigarh', 'Mohali', 'Panchkula')),
    -- A half-geocoded row (one coordinate set, the other not) is always a bug.
    CONSTRAINT ck_localities_latlng_together CHECK (
        (latitude IS NULL AND longitude IS NULL) OR (latitude IS NOT NULL AND longitude IS NOT NULL)
    ),
    CONSTRAINT ck_localities_lat_range CHECK (latitude IS NULL OR (latitude BETWEEN -90 AND 90)),
    CONSTRAINT ck_localities_lng_range CHECK (longitude IS NULL OR (longitude BETWEEN -180 AND 180))
);

CREATE INDEX idx_localities_city ON localities (city);
-- Supports "which localities still need geocoding".
CREATE INDEX idx_localities_ungeocoded ON localities (id) WHERE latitude IS NULL;
