-- Phase 1: seed Tricity localities, NAMES ONLY.
--
-- latitude/longitude are deliberately left NULL. Coordinates drive the distance sort and
-- the 3 km radius, so a plausible-but-wrong coordinate does not fail loudly — it quietly
-- puts the wrong tutor at the top of a parent's results, and nobody can tell which of the
-- ~150 rows is at fault. They are therefore resolved by an explicit geocoding pass
-- (LocalityGeocodingService, POST /api/admin/localities/geocode) which records what it
-- resolved and what it could not.
--
-- Until a row is geocoded it is still useful: it is a valid autocomplete entry and a valid
-- label. It just cannot participate in distance ranking, and search must say so rather
-- than pretend the locality is empty.
--
-- Chandigarh has no Sector 13 (it was skipped in Le Corbusier's plan, and is not a data
-- entry mistake). Chandigarh sectors run 1-12 and 14-56.

INSERT INTO localities (name, city) VALUES
    ('Sector 1, Chandigarh',   'Chandigarh'),
    ('Sector 2, Chandigarh',   'Chandigarh'),
    ('Sector 3, Chandigarh',   'Chandigarh'),
    ('Sector 4, Chandigarh',   'Chandigarh'),
    ('Sector 5, Chandigarh',   'Chandigarh'),
    ('Sector 6, Chandigarh',   'Chandigarh'),
    ('Sector 7, Chandigarh',   'Chandigarh'),
    ('Sector 8, Chandigarh',   'Chandigarh'),
    ('Sector 9, Chandigarh',   'Chandigarh'),
    ('Sector 10, Chandigarh',  'Chandigarh'),
    ('Sector 11, Chandigarh',  'Chandigarh'),
    ('Sector 12, Chandigarh',  'Chandigarh'),
    ('Sector 14, Chandigarh',  'Chandigarh'),
    ('Sector 15, Chandigarh',  'Chandigarh'),
    ('Sector 16, Chandigarh',  'Chandigarh'),
    ('Sector 17, Chandigarh',  'Chandigarh'),
    ('Sector 18, Chandigarh',  'Chandigarh'),
    ('Sector 19, Chandigarh',  'Chandigarh'),
    ('Sector 20, Chandigarh',  'Chandigarh'),
    ('Sector 21, Chandigarh',  'Chandigarh'),
    ('Sector 22, Chandigarh',  'Chandigarh'),
    ('Sector 23, Chandigarh',  'Chandigarh'),
    ('Sector 24, Chandigarh',  'Chandigarh'),
    ('Sector 25, Chandigarh',  'Chandigarh'),
    ('Sector 26, Chandigarh',  'Chandigarh'),
    ('Sector 27, Chandigarh',  'Chandigarh'),
    ('Sector 28, Chandigarh',  'Chandigarh'),
    ('Sector 29, Chandigarh',  'Chandigarh'),
    ('Sector 30, Chandigarh',  'Chandigarh'),
    ('Sector 31, Chandigarh',  'Chandigarh'),
    ('Sector 32, Chandigarh',  'Chandigarh'),
    ('Sector 33, Chandigarh',  'Chandigarh'),
    ('Sector 34, Chandigarh',  'Chandigarh'),
    ('Sector 35, Chandigarh',  'Chandigarh'),
    ('Sector 36, Chandigarh',  'Chandigarh'),
    ('Sector 37, Chandigarh',  'Chandigarh'),
    ('Sector 38, Chandigarh',  'Chandigarh'),
    ('Sector 39, Chandigarh',  'Chandigarh'),
    ('Sector 40, Chandigarh',  'Chandigarh'),
    ('Sector 41, Chandigarh',  'Chandigarh'),
    ('Sector 42, Chandigarh',  'Chandigarh'),
    ('Sector 43, Chandigarh',  'Chandigarh'),
    ('Sector 44, Chandigarh',  'Chandigarh'),
    ('Sector 45, Chandigarh',  'Chandigarh'),
    ('Sector 46, Chandigarh',  'Chandigarh'),
    ('Sector 47, Chandigarh',  'Chandigarh'),
    ('Sector 48, Chandigarh',  'Chandigarh'),
    ('Sector 49, Chandigarh',  'Chandigarh'),
    ('Sector 50, Chandigarh',  'Chandigarh'),
    ('Sector 51, Chandigarh',  'Chandigarh'),
    ('Sector 52, Chandigarh',  'Chandigarh'),
    ('Sector 53, Chandigarh',  'Chandigarh'),
    ('Sector 54, Chandigarh',  'Chandigarh'),
    ('Sector 55, Chandigarh',  'Chandigarh'),
    ('Sector 56, Chandigarh',  'Chandigarh'),
    ('Manimajra',              'Chandigarh'),
    ('Dhanas',                 'Chandigarh'),
    ('Maloya',                 'Chandigarh'),
    ('Ram Darbar',             'Chandigarh'),
    ('Burail',                 'Chandigarh'),
    ('Attawa',                 'Chandigarh'),
    ('Badheri',                'Chandigarh'),
    ('Kajheri',                'Chandigarh'),
    ('Palsora',                'Chandigarh'),
    ('Hallo Majra',            'Chandigarh'),
    ('Daria',                  'Chandigarh'),
    ('Raipur Khurd',           'Chandigarh'),
    ('Kishangarh',             'Chandigarh'),
    ('Khuda Ali Sher',         'Chandigarh'),
    ('Khuda Lahora',           'Chandigarh'),
    ('Dadu Majra',             'Chandigarh'),
    ('Industrial Area Phase 1, Chandigarh', 'Chandigarh'),
    ('Industrial Area Phase 2, Chandigarh', 'Chandigarh'),
    ('IT Park, Chandigarh',    'Chandigarh');

INSERT INTO localities (name, city) VALUES
    ('Phase 1, Mohali',        'Mohali'),
    ('Phase 2, Mohali',        'Mohali'),
    ('Phase 3A, Mohali',       'Mohali'),
    ('Phase 3B1, Mohali',      'Mohali'),
    ('Phase 3B2, Mohali',      'Mohali'),
    ('Phase 4, Mohali',        'Mohali'),
    ('Phase 5, Mohali',        'Mohali'),
    ('Phase 6, Mohali',        'Mohali'),
    ('Phase 7, Mohali',        'Mohali'),
    ('Phase 8, Mohali',        'Mohali'),
    ('Phase 9, Mohali',        'Mohali'),
    ('Phase 10, Mohali',       'Mohali'),
    ('Phase 11, Mohali',       'Mohali'),
    ('Sector 66, Mohali',      'Mohali'),
    ('Sector 67, Mohali',      'Mohali'),
    ('Sector 68, Mohali',      'Mohali'),
    ('Sector 69, Mohali',      'Mohali'),
    ('Sector 70, Mohali',      'Mohali'),
    ('Sector 71, Mohali',      'Mohali'),
    ('Sector 76, Mohali',      'Mohali'),
    ('Sector 77, Mohali',      'Mohali'),
    ('Sector 78, Mohali',      'Mohali'),
    ('Sector 79, Mohali',      'Mohali'),
    ('Sector 80, Mohali',      'Mohali'),
    ('Sector 82, Mohali',      'Mohali'),
    ('Sector 91, Mohali',      'Mohali'),
    ('Sector 115, Mohali',     'Mohali'),
    ('Sector 116, Mohali',     'Mohali'),
    ('Sector 117, Mohali',     'Mohali'),
    ('Aerocity, Mohali',       'Mohali'),
    ('Mataur',                 'Mohali'),
    ('Kumbra',                 'Mohali'),
    ('Sohana',                 'Mohali'),
    ('Balongi',                'Mohali'),
    ('Landran',                'Mohali'),
    ('Sunny Enclave, Kharar',  'Mohali'),
    ('Gillco Valley, Kharar',  'Mohali'),
    ('TDI City, Mohali',       'Mohali'),
    ('Kharar',                 'Mohali'),
    ('Zirakpur',               'Mohali'),
    ('Dhakoli, Zirakpur',      'Mohali'),
    ('VIP Road, Zirakpur',     'Mohali'),
    ('Peer Muchalla, Zirakpur','Mohali'),
    ('Dera Bassi',             'Mohali'),
    ('Banur',                  'Mohali'),
    ('New Chandigarh, Mullanpur', 'Mohali');

INSERT INTO localities (name, city) VALUES
    ('Sector 1, Panchkula',    'Panchkula'),
    ('Sector 2, Panchkula',    'Panchkula'),
    ('Sector 3, Panchkula',    'Panchkula'),
    ('Sector 4, Panchkula',    'Panchkula'),
    ('Sector 5, Panchkula',    'Panchkula'),
    ('Sector 6, Panchkula',    'Panchkula'),
    ('Sector 7, Panchkula',    'Panchkula'),
    ('Sector 8, Panchkula',    'Panchkula'),
    ('Sector 9, Panchkula',    'Panchkula'),
    ('Sector 10, Panchkula',   'Panchkula'),
    ('Sector 11, Panchkula',   'Panchkula'),
    ('Sector 12, Panchkula',   'Panchkula'),
    ('Sector 12A, Panchkula',  'Panchkula'),
    ('Sector 14, Panchkula',   'Panchkula'),
    ('Sector 15, Panchkula',   'Panchkula'),
    ('Sector 16, Panchkula',   'Panchkula'),
    ('Sector 17, Panchkula',   'Panchkula'),
    ('Sector 18, Panchkula',   'Panchkula'),
    ('Sector 19, Panchkula',   'Panchkula'),
    ('Sector 20, Panchkula',   'Panchkula'),
    ('Sector 21, Panchkula',   'Panchkula'),
    ('Sector 25, Panchkula',   'Panchkula'),
    ('Sector 26, Panchkula',   'Panchkula'),
    ('Sector 27, Panchkula',   'Panchkula'),
    ('Sector 28, Panchkula',   'Panchkula'),
    ('MDC Sector 4, Panchkula','Panchkula'),
    ('MDC Sector 5, Panchkula','Panchkula'),
    ('Amravati Enclave, Panchkula', 'Panchkula'),
    ('Budanpur',               'Panchkula'),
    ('Pinjore',                'Panchkula'),
    ('Kalka',                  'Panchkula'),
    ('Barwala',                'Panchkula'),
    ('Raipur Rani',            'Panchkula');
