-- Phase 1: the verification record behind the public "Verified" badge.
--
-- PRIVACY -- READ BEFORE ADDING A COLUMN HERE.
--
-- We do not store ID images and we do not store full ID numbers. Not an encrypted copy,
-- not a hash, not "temporarily". Holding Aadhaar or other government ID data makes Padhora
-- a custodian of sensitive personal data under the DPDP Act, and that exposure buys us
-- nothing a human eyeballing the card in a verification call does not already give us.
--
-- What we keep is the evidence that a check happened: which kind of document was shown,
-- its last four digits so we can refer to it again, and whether the name matched. The
-- CHECK constraint on id_last4 is deliberate and load-bearing -- it makes it impossible
-- for a full ID number to be written into this column by mistake, including by future
-- code that has forgotten this comment exists.

CREATE TABLE verifications (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tutor_id              BIGINT NOT NULL,

    -- Step 1: the tutor proved they hold the phone number on the listing.
    phone_verified_at     TIMESTAMP(6) WITH TIME ZONE,

    -- Step 2: a government ID was seen. Metadata only -- never the document, never the
    -- full number.
    id_type               VARCHAR(40),
    id_last4              VARCHAR(4),
    name_matched          BOOLEAN,

    -- Step 3: the locality on the listing is where they actually teach.
    locality_confirmed    BOOLEAN NOT NULL DEFAULT FALSE,

    -- Step 4: someone at Padhora actually spoke to them.
    call_completed_at     TIMESTAMP(6) WITH TIME ZONE,
    call_notes            VARCHAR(1000),

    -- Set only when every step above is done. Mirrored onto tutors.verified_at, which is
    -- what the public badge reads.
    verified_at           TIMESTAMP(6) WITH TIME ZONE,
    verified_by           VARCHAR(120),

    created_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),

    CONSTRAINT verifications_pkey PRIMARY KEY (id),
    CONSTRAINT uq_verifications_tutor UNIQUE (tutor_id),
    CONSTRAINT fk_verifications_tutor FOREIGN KEY (tutor_id) REFERENCES tutors (id) ON DELETE CASCADE,

    -- Exactly four digits, or nothing. This is the DPDP guardrail; do not relax it.
    CONSTRAINT ck_verifications_id_last4 CHECK (id_last4 IS NULL OR id_last4 ~ '^[0-9]{4}$'),

    CONSTRAINT ck_verifications_id_type CHECK (
        id_type IS NULL OR id_type IN ('AADHAAR', 'PAN', 'VOTER_ID', 'DRIVING_LICENCE', 'PASSPORT')
    ),

    -- A tutor cannot be marked verified without the checks that make the badge mean
    -- something. The badge is the only real promise on the parent-facing page.
    CONSTRAINT ck_verifications_complete CHECK (
        verified_at IS NULL OR (
            phone_verified_at IS NOT NULL
            AND id_type IS NOT NULL
            AND id_last4 IS NOT NULL
            AND name_matched IS TRUE
            AND locality_confirmed IS TRUE
            AND call_completed_at IS NOT NULL
        )
    )
);

CREATE INDEX idx_verifications_verified_at ON verifications (verified_at);
