-- Phase 3 (partial): unmet demand capture - "catch the parent when we have no tutor".
--
-- Distinct from `enquiries`, which is always tied to a specific tutor. A parent_request has
-- NO tutor at submission time - that is the whole point. It exists because, at current
-- supply, a parent who searches and finds nothing today just leaves, and we learn nothing:
-- not that they came, not what locality they wanted, not what class or subject. This table
-- is what lets that visit become data instead of a silent bounce.
--
-- Matching a request to a tutor is deliberately MANUAL (see matched_tutor_id below) - no
-- automated matching table or job. At this volume a person does it better, and doing it by
-- hand is itself how we learn which localities/subjects need more supply.

CREATE TABLE parent_requests (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

    -- Required: the two things without which this request cannot be acted on at all - no way
    -- to reach the parent, and no idea where to even look for a tutor.
    parent_phone     VARCHAR(20)  NOT NULL,
    locality_text    VARCHAR(150) NOT NULL,

    -- Optional: a parent may not know the exact class, or may be open on subject/mode. Forcing
    -- these would add friction to the one form this feature exists to keep frictionless.
    -- Plain FK columns, no JPA relations - matches the rest of this codebase (see Enquiry).
    grade_id         BIGINT REFERENCES grades (id),
    subject_id       BIGINT REFERENCES subjects (id),
    mode             VARCHAR(60),

    -- Carried through silently from the search box's own locality autocomplete when
    -- available (Places or "use my location") - not additional form fields, since the
    -- roadmap is explicit that phone/locality/class/subject/mode is the whole form. Lets
    -- admin plot demand on a map without asking the parent for anything more.
    latitude         DOUBLE PRECISION,
    longitude        DOUBLE PRECISION,

    status           VARCHAR(20) NOT NULL DEFAULT 'NEW',

    -- Set once an admin manually pairs this request with a tutor. Nullable and reassignable -
    -- the first match doesn't always pan out, and there is no automation deciding this.
    matched_tutor_id BIGINT REFERENCES tutors (id),
    matched_at       TIMESTAMP(6) WITH TIME ZONE,

    -- Free-text working notes for whoever is matching these by hand, e.g. "called, no answer".
    admin_notes      VARCHAR(1000),

    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),

    CONSTRAINT parent_requests_pkey PRIMARY KEY (id),
    CONSTRAINT ck_parent_requests_status CHECK (status IN ('NEW', 'MATCHED', 'CLOSED')),
    -- A half-set coordinate pair is always a bug, same rule as localities.
    CONSTRAINT ck_parent_requests_latlng_together CHECK (
        (latitude IS NULL AND longitude IS NULL) OR (latitude IS NOT NULL AND longitude IS NOT NULL)
    )
);

-- Admin inbox reads newest-first, optionally filtered by status - both need an index or this
-- becomes a full table scan the moment there is real volume.
CREATE INDEX idx_parent_requests_created_at ON parent_requests (created_at DESC);
CREATE INDEX idx_parent_requests_status ON parent_requests (status);
